### ISSUE TITLE
PHP Notice:  Undefined index: review in /mod/review/mod_form.php on line 49

### ISSUE THREAD

**Issue by mudrd8mz** [helg23/moodle-mod_review#1]
This line

https://github.com/helg23/moodle-mod_review/blob/23636145d389e4c6360ab5c30290e9ba209d8fe6/mod_form.php#L49

is causing the following PHP Notice when adding the first instance to the course:

```
PHP Notice:  Undefined index: review in /mod/review/mod_form.php on line 49
```

Please make sure to always have developer debugging enabled and watch for displayed noticed. Moodle has zero tolerance policy to these.

**Comment by helg23** [comment]
Error has been fixed with an additional check.
