### ISSUE TITLE
SQL failures on PostgreSQL

### ISSUE THREAD

**Issue by mudrd8mz** [helg23/moodle-mod_review#2]
After adding a new instance to a course, I get the SQL error:

![image](https://user-images.githubusercontent.com/85831/82542904-10858c80-9b53-11ea-86ec-8fb27ea0d370.png)

This is happening because "user" is a reserved word and cannot be used as the table alias in PostgreSQL. The solution that seems to work is to replace the "user" alias with something else such as "usr".

**Comment by helg23** [comment]
Alias for user table has been changed.
