### ISSUE TITLE
SQL failures in the rates_stat() method on PostgreSQL

### ISSUE THREAD

**Issue by mudrd8mz** [helg23/moodle-mod_review#3]
I am getting various SQL errors due to the query in the `rates_stat()` method under PostgreSQL.

![image](https://user-images.githubusercontent.com/85831/82543551-044dff00-9b54-11ea-80a0-a3a1ebbab369.png)

That one seems can be fixed by using cross-db compatible
```
SELECT  COUNT(id) AS amount,
```
(notice the AS and no quotes). However there are further issues with the `IFNULL` function which is a proprietary MySQL specific function. If you need such behaviour, you may need to use `COALESCE` or `CASE WHEN THEN` functions which are cross-db compatible.

**Comment by helg23** [comment]
Cross-db compatibility has been added to the SQL queries.
